package labtest;

public enum Mutation {
	OK,
	NO_NULL,
	NO_LOWERCASE,
	NO_UPPERCASE,
	MIN_PASSWORD_TOO_LONG,
	MIN_PASSWORD_TOO_SHORT,
	MISSING_DIGIT_TEST,
	MIN_USER_NAME_TOO_SHORT,
	MIN_USER_NAME_TOO_LONG,
	MAX_USER_NAME_TOO_SHORT,
	NO_USERNAME_ALPHA_CHECK,
	UPPER_CASE_NO_CHECK_FIRST,
	UPPER_CASE_NO_CHECK_LAST,
	LOWER_CASE_NO_CHECK_FIRST,
	LOWER_CASE_NO_CHECK_LAST,
	DIGIT_NO_CHECK_FIRST,
	DIGIT_NO_CHECK_LAST,
	END_MUTATIONS
}
	
	
	
	

